### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-1-infografia-Vanessacruzortiz#1]
![Infografia-Vanessa-Cruz](https://github.com/user-attachments/assets/9d47da6b-4155-404e-aa59-478a719ea2c7)

**Comment by MarcoRg06** [comment]
Tomando en cuenta la rúbrica tienes 18.57%.
Especificaciones;
- son 10 temas y tienes 5.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
